spring.application.name=myapp
cloudsentry.iam.access-key-age-days=90
cloudsentry.iam.unused-key-days=90
cloudsentry.iam.max-active-access-keys=2
cloudsentry.iam.minimum-password-length=12
# CloudSentry Cost Scanner
cloudsentry.cost.stopped-instance-days=30